### ISSUE TITLE
请教：为何解码时 需要将 + 替换为空格？

### ISSUE THREAD

**Issue by ctriver** [A-BenMao/pure-bash-bible-zh_CN#1]
urldecode() {
    # Usage: urldecode "string"
    : "${1//+/ }" #为何这里需要替换，不是很明白
    printf '%b\n' "${_//%/\\x}"
}
感谢前辈辛苦翻译，
如果有时间麻烦解答一下疑惑。：）

**Comment by A-BenMao** [comment]
这个就涉及到了百分比编码的一些规则了：
需要编码的特殊字符有： ':'，'/'，'?'，'#'，'['，']'，'@'，'!'，'$'，'&'，"'"，'('，')'，'*'，'+'，','，';'，'='，以及，'%' 本身. 其他的字符虽然可以进行编码但是不需要。
但是空格可能会被编码为‘+’，所以在解码的时候需要对“+”进行特殊处理。
详情请见[https://developer.mozilla.org/zh-CN/docs/Glossary/percent-encoding](https://developer.mozilla.org/zh-CN/docs/Glossary/percent-encoding)
